log_level = "debug"

keyslots = [
    { name = "logos2-opal", source = "stdin" },
    { name = "keypartition", source = "stdin" },
    { name = "keyfile_system", source = { partition = "keys", file = "/keyfile_system" } },
]

[[partitions]]
    name = "keys-encrypted"
    uuid = "30a65847-0e31-4c1c-85b1-3f6c9f9ff4e1"
    keyslot = "keypartition"
[[partitions]]
    name = "keys"
    parent = "keys-encrypted"
    uuid = "8a808821-3f29-402d-bdb8-a44dbd067b95"
[[partitions]]
    name = "samsung-1TB"
    uuid = "fa630800-b26d-43b9-a1ef-6c15d60abaa4"
    keyslot = "kefile_system"
[[partitions]]
    name = "lvm"
    parent = "samsung-1TB"
    uuid = "JUkRSn-MfRF-TYyw-o7or-VZce-GG3A-bO7K1r"
[[partitions]]
    name = "system"
    parent = "lvm"
    uuid = "fcecca1d-870f-4009-858f-728a175b47fa"

[[boot_entries]]
    name = "memtest86+"
    partition = "system"
    file = "/boot/EFI/Boot/memtest.efi"
[[boot_entries]]
    name = "Linux"
    partition = "system"
    file = "/vmlinuz-linux"
    initrd = [
        { partition = "system", file = "/initramfs-linux.img" },
        { partition = "system", file = "/amd-ucode.img" },
    ]
    additional_initrd_files = [
        { partition = "keys", file = "/keyfile_lvm", target_file = "/keyfile_lvm" },
        { partition = "keys", file = "/keyfile_lvm2_512G", target_file = "/keyfile_lvm2_512G" },
    ]
    options = "intel_iommu=on root=/dev/vg_lvm/system"
    default = true
