log_level = "trace"

keyslots = [
    { name = "logos2-opal", source = "stdin" },
    { name = "keypartition", source = "stdin" },
    { name = "keyfile_lvm", source = { partition = "keys", file = "/keyfile_lvm" } },
]

[[partitions]]
    name = "keys-encrypted"
    uuid = "49db1904-50bf-4b8e-922d-1030de11cac2"
    keyslot = "keypartition"
[[partitions]]
    name = "keys"
    parent = "keys-encrypted"
    uuid = "711148c9-e4cb-4fcf-b87a-02aaeca2267b"
[[partitions]]
    name = "samsung-1TB"
    uuid = "fa630800-b26d-43b9-a1ef-6c15d60abaa4"
    keyslot = "keyfile_lvm"
[[partitions]]
    name = "lvm"
    parent = "samsung-1TB"
    uuid = "JUkRSn-MfRF-TYyw-o7or-VZce-GG3A-bO7K1r"
[[partitions]]
    name = "system"
    parent = "lvm"
    uuid = "fcecca1d-870f-4009-858f-728a175b47fa"

[[boot_entries]]
    name = "memtest86+"
    partition = "system"
    file = "/boot/EFI/Boot/memtest.efi"
[[boot_entries]]
    name = "Linux"
    partition = "system"
    file = "/boot2/vmlinuz-linux-zen"
    initrd = [
        { partition = "system", file = "/boot2/initramfs-linux-zen.img" },
        { partition = "system", file = "/boot2/amd-ucode.img" },
    ]
    additional_initrd_files = [
        { partition = "keys", file = "/keyfile_lvm", target_file = "/keyfile_lvm" },
        { partition = "keys", file = "/keyfile_lvm2_512G", target_file = "/keyfile_lvm2_512G" },
    ]
    options = "intel_iommu=on root=/dev/vg_lvm/system systemd.debug-shell=1"
    default = true
